# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end
  lane :build do
    increment_version_code
    gradle(task: "clean assembleRelease")
    # Generate the changelog based on commit messages since your last tag
    changelog_from_git_commits

  end
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    # Generate the changelog based on commit messages since your last tag
    changelog_from_git_commits

    #crashlytics
    slack(message: 'Successfully distributed a new beta build')

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
  lane :beta_pgyer do
    build
    pgyer(api_key: ENV['pgyer_api_key'], user_key: ENV['pgyer_user_key'], password: ENV['pgyer_password'], install_type: "2")
    slack(message: 'Successfully distributed a new beta build')
  end
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
